version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

submodules:
  include: all
  recursive: false

sphinx:
  builder: html
  configuration: private-repo/docs/source/conf.py

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: private-repo
      extra_requirements:
        - dev