# docs/source/conf.py (Updated for i18n)

import os
import sys
# sys.path.insert(0, os.path.abspath('../../src'))  # API 文档需要 - Commented out for public docs

# -- Project information -----------------------------------------------------
project = 'PolyglotMol'
copyright = '2025, Xufan Gao'
author = 'Xufan Gao'
version = '0.0'
release = '0.0'

# -- General configuration ---------------------------------------------------
extensions = [
    "myst_parser",           # Support Markdown
    "sphinx.ext.autodoc",    # From docstrings
    "sphinx.ext.napoleon",   # Google/NumPy docstrings
    "sphinx.ext.intersphinx",# Link external docs
    "sphinx.ext.viewcode",   # Source links
    "sphinx.ext.githubpages",# GitHub Pages support
    "sphinxcontrib.mermaid", # Mermaid diagrams
    "sphinx.ext.todo",       # TODO notes
    "sphinx_design",         # <-- Added for grid directive
    'sphinx_copybutton',   # 代码块复制按钮
]

templates_path = ['_templates']
exclude_patterns = []

# -- Suppress warnings -------------------------------------------------------
suppress_warnings = [
    'myst.header',  # Suppress MyST header warnings
    'autosectionlabel.*',  # Suppress autosectionlabel warnings
    'ref.any',  # Suppress some reference warnings
    'toc.excluded',  # Suppress excluded toctree warnings
    'app.add_node',  # Suppress app node warnings
    'app.add_directive',  # Suppress app directive warnings
]

# -- Autodoc default options -------------------------------------------------
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__'
}

# -- Autodoc import mock -----------------------------------------------------
autodoc_mock_imports = [
    'preprocessing',  # Failed import in models
    'topological',    # Failed import in representations
    'tensorflow',     # DeepChem optional dependency
    'torch_geometric', # DeepChem optional dependency
    'lightning',      # DeepChem optional dependency
    'jax',            # DeepChem optional dependency
    'unimol_tools',   # Optional spatial dependency
    'dscribe',        # Optional spatial dependency
    'ase',            # ASE dependency for dscribe
]

# -- HTML output options -----------------------------------------------------
html_show_sourcelink = True
html_show_sphinx = True
html_show_copyright = True

# -- MyST Parser configuration -----------------------------------------------
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

myst_enable_extensions = [
    "amsmath",      # 支持 LaTeX 数学环境
    "dollarmath",   # 支持 $...$ 和 $$...$$ 数学公式
    "tasklist",     # 支持 Markdown 任务列表 [-] [x]
    "html_image",   # 支持 HTML <img> 标签
    "colon_fence",  # 支持 ```{directive} 语法
    # "linkify",      # 自动识别 URL 为链接 (可选)
    # "substitution", # 支持替换/变量 (可选)
]
myst_heading_anchors = 3 # 自动为 H1, H2, H3 标题生成锚点

# -- Autodoc configuration ---------------------------------------------------
autodoc_member_order = 'bysource' # 按源代码顺序排列成员
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# -- Internationalization (i18n) configuration -------------------------------
# 主要编写语言 (The language for content autogenerated by Sphinx)
language = 'en' # 先用英文编写，后续翻译成中文

# 存放 .po / .mo 文件的目录 (Directory where translation files (.po/.mo) reside)
# 相对于 source 目录 (Relative to the source directory)
locale_dirs = ['locales/']

# 如果为 False，gettext 将为每个节点创建一个 .pot 文件，更易于管理
# If False, gettext creates individual .pot files per document, easier to manage
gettext_compact = False

# Gettext 输出文件名格式 (Output filename format for gettext)
# gettext_uuid = True # 使用 UUID 避免文件名冲突 (可选)

# -- ToDo configuration ------------------------------------------------------
todo_include_todos = True

# -- Intersphinx configuration -----------------------------------------------
# 链接到 Python, NumPy, RDKit, DeepChem 等文档
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'rdkit': ('https://www.rdkit.org/docs/', None),
    'deepchem': ('https://deepchem.readthedocs.io/en/latest/', None),
    'pandas': ('https://pandas.pydata.org/pandas-docs/stable/', None),
    # 添加其他你可能引用的库
}

# -- Options for HTML output -------------------------------------------------
html_theme = 'furo' # 使用 Furo 主题
html_static_path = ['_static'] # 存放自定义 CSS, JS, 图片等
# html_logo = "_static/logo.png" # 如果你有 Logo 图片
# html_favicon = "_static/favicon.ico" # 如果你有 Favicon

# Furo 主题选项 (可选)
# html_theme_options = {
#     "light_css_variables": {
#         "color_brand_primary": "#...",
#         "color_brand_content": "#...",
#     },
#     "dark_css_variables": {
#         "color_brand_primary": "#...",
#         "color_brand_content": "#...",
#     },
#     "source_repository": "[https://github.com/your_username/PolyglotMol/](https://github.com/your_username/PolyglotMol/)",
#     "source_branch": "main",
#     "source_directory": "docs/source/",
# }